# Generated by Django 3.1.5 on 2021-01-10 14:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0005_auto_20210110_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='Images_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(max_length=60),
        ),
    ]
