# Generated by Django 3.1.5 on 2021-01-10 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0006_auto_20210110_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
